config/routes.rb
Rails.application.routes.draw do

  resources :occupations

  resources :lgas

  resources :states

  resources :nationalities

  resources :religions

  resources :patients

  resources :consultants

  resources :clinics

  root "patients#index"

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  belongs_to :clinic
  has_many :patients
  validates :name, :clinic, presence: true
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  before_action :set_consultant, only: [:show, :edit, :update, :destroy]

  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
  end

  # GET /consultants/new
  def new
    @consultant = Consultant.new
  end

  # GET /consultants/1/edit
  def edit
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(consultant_params)

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to consultants_path, notice: 'Consultant was successfully created.' }
        format.json { render :index, status: :created, location: consultants_path }
      else
        format.html { render :new }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultants/1
  # PATCH/PUT /consultants/1.json
  def update
    respond_to do |format|
      if @consultant.update(consultant_params)
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultant }
      else
        format.html { render :edit }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant.destroy
    respond_to do |format|
      format.html { redirect_to consultants_url, notice: 'Consultant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultant
      @consultant = Consultant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultant_params
      params.require(:consultant).permit(:name, :clinic_id)
    end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_form.html.erb
<%= form_for(@consultant) do |f| %>
  <% if @consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultant.errors.count, "error") %> prohibited this consultant from being saved:</h2>

      <ul>
      <% @consultant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :clinic_id, "Clinic" %><br>
    <%= f.collection_select :clinic_id, Clinic.all, :id, :name, {prompt: "Choose clinic consultant belongs to"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consultants/edit.html.erb
<h1>Editing Consultant</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/consultants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Consultants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Clinic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultants.each do |consultant| %>
      <tr>
        <td><%= consultant.name %></td>
        <td><%= consultant.clinic.name %></td>
        <td><%= link_to 'Show', consultant %></td>
        <td><%= link_to 'Edit', edit_consultant_path(consultant) %></td>
        <td><%= link_to 'Destroy', consultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultant', new_consultant_path %>

app/views/consultants/new.html.erb
<h1>New Consultant</h1>

<%= render 'form' %>

<%= link_to 'Back', consultants_path %>

app/views/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @consultant.name %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @consultant.clinic.name %>
</p>

<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>