config/routes.rb
Rails.application.routes.draw do

  resources :occupations

  resources :lgas

  resources :states

  resources :nationalities

  resources :religions

  resources :patients

  resources :consultants

  resources :clinics

  root "patients#index"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	after_create :set_mrn
  belongs_to :consultant
  belongs_to :clinic
  validates :surname, :first_name, :phone, :address, :gender, :next_of_kin, :next_of_kin_phone, :consultant, :occupation, :state, :religion, presence: true
  belongs_to :occupation
  belongs_to :nationality
  belongs_to :religion
  belongs_to :state
  belongs_to :lga
   Gender = %w(Male Female)

   def set_mrn
   	update_attribute(:mrn, "P#{self.id}H")
   end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:mrn, :surname, :first_name, :middle_name, :gender, :dob, :address, :phone, :email, :next_of_kin, :next_of_kin_phone, :consultant_id, :clinic_id, :occupation_id, :religion_id, :nationality_id, :state_id, :lga_id)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, options_for_select(Patient::Gender), {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_field :dob %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :religion_id %><br>
    <%= f.collection_select :religion_id, Religion.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :occupation_id %><br>
    <%= f.collection_select :occupation_id, Occupation.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :state, "State of Residence" %><br>
    <%= f.collection_select :state_id, State.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :lga %><br>
    <%= f.collection_select :lga_id, Lga.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.collection_select :nationality_id, Nationality.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :next_of_kin %><br>
    <%= f.text_field :next_of_kin %>
  </div>
  <div class="field">
    <%= f.label :next_of_kin_phone %><br>
    <%= f.text_field :next_of_kin_phone %>
  </div>
  <div class="field">
    <%= f.label :consultant_id %><br>
    <%= f.collection_select :consultant_id, Consultant.all, :id, :name, {include_blank: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>MR No.</th>
      <th>Surname</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Gender</th>
      <th>Dob</th>
      <th>Consultant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.mrn %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.middle_name %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.consultant.name %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p><strong>MR No:</strong><%= @patient.mrn %></p>
<p>
  <strong>Surname:</strong>
  <%= @patient.surname %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @patient.middle_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>
<p>
  <strong>State:</strong>
  <%= @patient.state.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>
<p>
  <strong>Religion:</strong>
  <%= @patient.religion.name %>
</p>
<p>
  <strong>Occupation:</strong>
  <%= @patient.occupation.name %>
</p>
<p>
  <strong>Next of kin:</strong>
  <%= @patient.next_of_kin %>
</p>

<p>
  <strong>Next of kin phone:</strong>
  <%= @patient.next_of_kin_phone %>
</p>

<p>
  <strong>Consultant:</strong>
  <%= @patient.consultant.name %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>