config/routes.rb
Rails.application.routes.draw do

  resources :occupations

  resources :lgas

  resources :states

  resources :nationalities

  resources :religions

  resources :patients

  resources :consultants

  resources :clinics

  root "patients#index"

end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
	has_many :patients
	validates :name, presence: true
end

app/controllers/nationalities_controller.rb
class NationalitiesController < ApplicationController
  before_action :set_nationality, only: [:show, :edit, :update, :destroy]

  # GET /nationalities
  # GET /nationalities.json
  def index
    @nationalities = Nationality.all
  end

  # GET /nationalities/1
  # GET /nationalities/1.json
  def show
  end

  # GET /nationalities/new
  def new
    @nationality = Nationality.new
  end

  # GET /nationalities/1/edit
  def edit
  end

  # POST /nationalities
  # POST /nationalities.json
  def create
    @nationality = Nationality.new(nationality_params)

    respond_to do |format|
      if @nationality.save
        format.html { redirect_to nationalities_path, notice: 'Nationality was successfully created.' }
        format.json { render :index, status: :created, location: nationalities_path }
      else
        format.html { render :new }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nationalities/1
  # PATCH/PUT /nationalities/1.json
  def update
    respond_to do |format|
      if @nationality.update(nationality_params)
        format.html { redirect_to @nationality, notice: 'Nationality was successfully updated.' }
        format.json { render :show, status: :ok, location: @nationality }
      else
        format.html { render :edit }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nationalities/1
  # DELETE /nationalities/1.json
  def destroy
    @nationality.destroy
    respond_to do |format|
      format.html { redirect_to nationalities_url, notice: 'Nationality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nationality
      @nationality = Nationality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nationality_params
      params.require(:nationality).permit(:name)
    end
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/views/nationalities/_form.html.erb
<%= form_for(@nationality) do |f| %>
  <% if @nationality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nationality.errors.count, "error") %> prohibited this nationality from being saved:</h2>

      <ul>
      <% @nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nationalities/edit.html.erb
<h1>Editing Nationality</h1>

<%= render 'form' %>

<%= link_to 'Show', @nationality %> |
<%= link_to 'Back', nationalities_path %>

app/views/nationalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nationalities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nationalities.each do |nationality| %>
      <tr>
        <td><%= nationality.name %></td>
        <td><%= link_to 'Show', nationality %></td>
        <td><%= link_to 'Edit', edit_nationality_path(nationality) %></td>
        <td><%= link_to 'Destroy', nationality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nationality', new_nationality_path %>

app/views/nationalities/new.html.erb
<h1>New Nationality</h1>

<%= render 'form' %>

<%= link_to 'Back', nationalities_path %>

app/views/nationalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nationality.name %>
</p>

<%= link_to 'Edit', edit_nationality_path(@nationality) %> |
<%= link_to 'Back', nationalities_path %>